// @ts-check

/**
 * The sidebar is generated from the folders under website/docs/.
 * Do not list pages here: add a .md file to a folder (order it with
 * `sidebar_position` frontmatter) or add a folder with its own
 * `_category_.json`.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
